<a href="https://colab.research.google.com/github/atharva0074/Marketing-Data-Analytics/blob/main/Marketing_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_excel('/content/a1_Dataset_10Percent.xlsx')

In [ ]:
data.head()

ID  DemAffl  DemAge DemClusterGroup DemGender    DemReg DemTVReg  \
0  17147654      5.0     NaN             NaN       NaN       NaN      NaN   
1   8415498     15.0     NaN             NaN         M       NaN      NaN   
2  12107603      NaN     NaN             NaN         M  Midlands     East   
3  14400995      8.0    28.0             NaN         F       NaN      NaN   
4  28724674     14.0    67.0             NaN       NaN       NaN      NaN   

  LoyalClass  LoyalSpend  LoyalTime  TargetBuy  
0        Tin        0.01        5.0          0  
1       Gold     8000.00        5.0          1  
2        Tin        0.01        NaN          1  
3        Tin        0.01        NaN          1  
4        Tin        0.01        7.0          0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22223 entries, 0 to 22222
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ID               22223 non-null  int64  
 1   DemAffl          21138 non-null  float64
 2   DemAge           20715 non-null  float64
 3   DemClusterGroup  21549 non-null  object 
 4   DemGender        19711 non-null  object 
 5   DemReg           21758 non-null  object 
 6   DemTVReg         21758 non-null  object 
 7   LoyalClass       22223 non-null  object 
 8   LoyalSpend       22223 non-null  float64
 9   LoyalTime        21942 non-null  float64
 10  TargetBuy        22223 non-null  int64  
dtypes: float64(4), int64(2), object(5)
memory usage: 1.9+ MB


In [ ]:
# Analysing Null values in dataset

In [ ]:
data.isna().sum()

ID                    0
DemAffl            1085
DemAge             1508
DemClusterGroup     674
DemGender          2512
DemReg              465
DemTVReg            465
LoyalClass            0
LoyalSpend            0
LoyalTime           281
TargetBuy             0
dtype: int64

In [ ]:
# filling the missing value with mean or the mode

In [ ]:
data['DemAffl']=data['DemAffl'].fillna(data['DemAffl'].mode()[0])
data['DemAge']=data['DemAge'].fillna(data['DemAge'].mode()[0])
data['DemClusterGroup']=data['DemClusterGroup'].fillna(data['DemClusterGroup'].mode()[0])
data['DemGender']=data['DemGender'].fillna(data['DemGender'].mode()[0])
data['DemReg']=data['DemReg'].fillna(data['DemReg'].mode()[0])
data['DemTVReg']=data['DemTVReg'].fillna(data['DemTVReg'].mode()[0])
data['LoyalTime']=data['LoyalTime'].fillna(data['LoyalTime'].mean())


In [ ]:
data.head()

ID  DemAffl  DemAge DemClusterGroup DemGender      DemReg DemTVReg  \
0  17147654      5.0    51.0               C         F  South East   London   
1   8415498     15.0    51.0               C         M  South East   London   
2  12107603      8.0    51.0               C         M    Midlands     East   
3  14400995      8.0    28.0               C         F  South East   London   
4  28724674     14.0    67.0               C         F  South East   London   

  LoyalClass  LoyalSpend  LoyalTime  TargetBuy  
0        Tin        0.01        5.0          0  
1       Gold     8000.00        5.0          1  
2        Tin        0.01        5.0          1  
3        Tin        0.01        5.0          1  
4        Tin        0.01        7.0          0

In [ ]:
# using label encoding to convert categorical data into numerical data

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['DemClusterGroup']=le.fit_transform(data['DemClusterGroup'])
data['DemGender']=le.fit_transform(data['DemGender'])
data['DemReg']=le.fit_transform(data['DemReg'])
data['DemTVReg']=le.fit_transform(data['DemTVReg'])
data['LoyalClass']=le.fit_transform(data['LoyalClass'])

In [ ]:
data['DemClusterGroup'].unique()


array([2, 1, 4, 3, 5, 0, 6])

In [ ]:
data['DemGender'].unique()


array([0, 1, 2])

In [ ]:
data['DemReg'].unique()


array([3, 0, 1, 4, 2])

In [ ]:
data['DemTVReg'].unique()

array([ 3,  2, 10,  8, 12, 11,  7,  4,  9,  5,  6,  1,  0])

In [ ]:

data['LoyalClass'].unique()

array([3, 0, 2, 1])

In [ ]:
# count of customers in each loyal_class
data['LoyalClass'].value_counts()

LoyalClass
2    8572
3    6487
0    6324
1     840
Name: count, dtype: int64

In [ ]:
data.head()

ID  DemAffl  DemAge  DemClusterGroup  DemGender  DemReg  DemTVReg  \
0  17147654      5.0    51.0                2          0       3         3   
1   8415498     15.0    51.0                2          1       3         3   
2  12107603      8.0    51.0                2          1       0         2   
3  14400995      8.0    28.0                2          0       3         3   
4  28724674     14.0    67.0                2          0       3         3   

   LoyalClass  LoyalSpend  LoyalTime  TargetBuy  
0           3        0.01        5.0          0  
1           0     8000.00        5.0          1  
2           3        0.01        5.0          1  
3           3        0.01        5.0          1  
4           3        0.01        7.0          0

In [ ]:
df=data.drop(['ID'],axis=1)

In [ ]:
df.head()

DemAffl  DemAge  DemClusterGroup  DemGender  DemReg  DemTVReg  LoyalClass  \
0      5.0    51.0                2          0       3         3           3   
1     15.0    51.0                2          1       3         3           0   
2      8.0    51.0                2          1       0         2           3   
3      8.0    28.0                2          0       3         3           3   
4     14.0    67.0                2          0       3         3           3   

   LoyalSpend  LoyalTime  TargetBuy  
0        0.01        5.0          0  
1     8000.00        5.0          1  
2        0.01        5.0          1  
3        0.01        5.0          1  
4        0.01        7.0          0

In [ ]:
x=df.drop(['TargetBuy'],axis=1) #independent variables
y=df['TargetBuy'] #dependent variables

In [ ]:
#spliting the data into train split

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()

In [ ]:
classifier.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
predictions=classifier.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,predictions)

In [ ]:
ac=accuracy_score(y_test,predictions)

In [ ]:
print(cm)

[[3166  162]
 [ 735  382]]


In [ ]:
print(ac)

0.7982002249718785
